// app/layout.tsx (or layout.jsx)
import './globals.css'
import { ReactNode } from 'react';

export const metadata = {
  title: 'Your App',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}


// 'use client';
// import { useState } from 'react';
// import Sidebar from '../components/ui/Sidebar';
// import GeneratedArticles from './dashboard/generated-articles/GeneratedArticles';

// export default function DashboardLayout() {
//   const [activeSubPage, setActiveSubPage] = useState('');

//   const renderContent = () => {
//     switch (activeSubPage) {
//       case 'Generated Articles':
//         return <GeneratedArticles />;
//       default:
//         return <div className="p-8">Select a section</div>;
//     }
//   };

//   return (
//     <div className="flex">
//       <Sidebar setActiveSubPage={setActiveSubPage} />
//       <main className="ml-64 w-full">{renderContent()}</main>
//     </div>
//   );
// }





// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
